'use strict';

(() => {
  const MODE_ORDER = ['system', 'light', 'dark'];
  const STYLE_ORDER = [
    'paper-desk',
    'ivory-index',
    'harbor-mist',
    'clay-notes',
    'botanical-folio',
    'porcelain-atlas',
    'nocturne-observatory',
    'vermilion-seal',
  ];

  // Removed style IDs remain compatibility aliases so existing preferences
  // migrate to the closest new material rather than falling back to default.
  const STYLE_ALIASES = {
    paper: 'paper-desk',
    ivory: 'ivory-index',
    sage: 'ivory-index',
    mist: 'harbor-mist',
    blush: 'clay-notes',
    midnight: 'harbor-mist',
    editorial: 'porcelain-atlas',
    'editorial-grid': 'porcelain-atlas',
    archive: 'botanical-folio',
    'archive-ledger': 'botanical-folio',
    botanical: 'botanical-folio',
    porcelain: 'porcelain-atlas',
    nocturne: 'nocturne-observatory',
    vermilion: 'vermilion-seal',
  };

  const LEGACY_PALETTE_IDS = {
    'paper-desk': 'paper',
    'ivory-index': 'ivory',
    'harbor-mist': 'mist',
    'clay-notes': 'blush',
    'botanical-folio': 'botanical',
    'porcelain-atlas': 'porcelain',
    'nocturne-observatory': 'nocturne',
    'vermilion-seal': 'vermilion',
  };

  const LEGACY_THEME_MIGRATION = {
    paper: { mode: 'light', styleId: 'paper-desk' },
    sage: { mode: 'light', styleId: 'ivory-index' },
    mist: { mode: 'light', styleId: 'harbor-mist' },
    blush: { mode: 'light', styleId: 'clay-notes' },
    midnight: { mode: 'dark', styleId: 'harbor-mist' },
    editorial: { mode: 'light', styleId: 'porcelain-atlas' },
    archive: { mode: 'light', styleId: 'botanical-folio' },
    'editorial-grid': { mode: 'light', styleId: 'porcelain-atlas' },
    'archive-ledger': { mode: 'light', styleId: 'botanical-folio' },
  };

  const REQUIRED_TONE_TOKENS = [
    '--ink',
    '--paper',
    '--warm-gray',
    '--muted',
    '--th-color-text-secondary',
    '--accent-amber',
    '--accent-chamomile',
    '--accent-slate',
    '--accent-rose',
    '--workspace-accent',
    '--workspace-accent-soft',
    '--workspace-accent-border',
    '--workspace-accent-contrast',
    '--status-active',
    '--status-cooling',
    '--status-abandoned',
    '--card-bg',
  ];

  const BOOK_SERIF = "'Iowan Old Style', Baskerville, 'Songti SC', STSong, 'Noto Serif CJK SC', 'Source Han Serif SC', Georgia, serif";
  const CJK_SERIF = "'Songti SC', STSong, 'Noto Serif CJK SC', 'Source Han Serif SC', 'Iowan Old Style', Baskerville, Georgia, serif";

  const BASE_STYLE_TOKENS = {
    '--th-font-ui': 'var(--th-font-serif)',
    '--th-font-display': "'Test Tiempos Text', '方正FW筑紫A老明朝 简', serif",
    '--th-font-section': "'Test Tiempos Text', '方正FW筑紫A老明朝 简', serif",
    '--th-display-weight': '500',
    '--th-display-tracking': '-0.035em',
    '--th-section-tracking': '-0.018em',
    '--th-container-max': '1260px',
    '--th-container-padding-x': '32px',
    '--th-column-gap': '42px',
    '--th-section-gap': '22px',
    '--th-card-gap': '12px',
    '--th-item-padding-y': '14px',
    '--th-item-padding-x': '16px',
    '--th-panel-radius': 'var(--th-radius-xl)',
    '--th-card-radius': 'var(--th-radius-lg)',
    '--th-control-radius': 'var(--th-radius-pill)',
    '--th-field-radius': 'var(--th-radius-pill)',
    '--th-border-width': 'var(--th-border-width-hairline)',
    '--th-page-texture-opacity': '0.03',
    '--th-surface-blur': '10px',
    '--th-item-shadow': '0 14px 28px color-mix(in srgb, var(--workspace-accent) 6%, transparent)',
    '--th-item-shadow-hover': '0 18px 34px color-mix(in srgb, var(--workspace-accent) 10%, transparent)',
    '--th-floating-shadow': '0 24px 58px color-mix(in srgb, var(--workspace-accent) 16%, transparent)',
    '--th-hover-lift': '-1px',
    '--th-divider-opacity': '62%',
  };

  const STYLE_DEFINITIONS = {
    'paper-desk': {
      name: 'Paper desk',
      nameKey: 'themeStylePaperDeskName',
      meta: 'Warm, literary, composed',
      metaKey: 'themeStylePaperDeskMeta',
      shortMeta: 'Parchment',
      tokens: { ...BASE_STYLE_TOKENS },
      light: {
        '--ink': '#211c17', '--paper': '#f6f0e7', '--warm-gray': '#ded4c8', '--muted': '#81776e', '--th-color-text-secondary': '#645b53',
        '--accent-amber': '#9d6840', '--accent-chamomile': '#b89863', '--accent-slate': '#66727d', '--accent-rose': '#9d655c',
        '--workspace-accent': '#7e5d3e', '--workspace-accent-soft': '#eadccc', '--workspace-accent-border': '#c9a986', '--workspace-accent-contrast': '#fffaf2',
        '--status-active': '#526f55', '--status-cooling': '#9a7538', '--status-abandoned': '#9d655c', '--card-bg': '#fffaf2',
      },
      dark: {
        '--ink': '#ebe2d6', '--paper': '#17130f', '--warm-gray': '#2b241d', '--muted': '#94877a', '--th-color-text-secondary': '#b8ada2',
        '--accent-amber': '#c28a5a', '--accent-chamomile': '#c9ad75', '--accent-slate': '#84909a', '--accent-rose': '#bd7770',
        '--workspace-accent': '#b4865e', '--workspace-accent-soft': '#2c241d', '--workspace-accent-border': '#6b563f', '--workspace-accent-contrast': '#17130f',
        '--status-active': '#86a184', '--status-cooling': '#c49a5f', '--status-abandoned': '#c98279', '--card-bg': '#211b15',
      },
    },
    'ivory-index': {
      name: 'Ivory index',
      nameKey: 'themeStyleIvoryIndexName',
      meta: 'Precise, compact, content-first',
      metaKey: 'themeStyleIvoryIndexMeta',
      shortMeta: 'Index',
      tokens: {
        ...BASE_STYLE_TOKENS,
        '--th-font-ui': BOOK_SERIF,
        '--th-font-display': BOOK_SERIF,
        '--th-font-section': BOOK_SERIF,
        '--th-display-weight': '500',
        '--th-display-tracking': '-0.018em',
        '--th-section-tracking': '0.06em',
        '--th-container-max': '1220px',
        '--th-column-gap': '34px',
        '--th-section-gap': '18px',
        '--th-card-gap': '8px',
        '--th-item-padding-y': '11px',
        '--th-item-padding-x': '13px',
        '--th-panel-radius': 'var(--th-radius-md)',
        '--th-card-radius': 'var(--th-radius-md)',
        '--th-control-radius': 'var(--th-radius-sm)',
        '--th-field-radius': 'var(--th-radius-md)',
        '--th-page-texture-opacity': '0.012',
        '--th-surface-blur': '0px',
        '--th-item-shadow': 'none',
        '--th-item-shadow-hover': '0 8px 20px color-mix(in srgb, var(--workspace-accent) 7%, transparent)',
        '--th-hover-lift': '0px',
        '--th-divider-opacity': '82%',
      },
      light: {
        '--ink': '#1d2024', '--paper': '#f6f7f9', '--warm-gray': '#e1e4e8', '--muted': '#737a83', '--th-color-text-secondary': '#59616a',
        '--accent-amber': '#8c7650', '--accent-chamomile': '#9b9675', '--accent-slate': '#5f6b78', '--accent-rose': '#916d70',
        '--workspace-accent': '#596572', '--workspace-accent-soft': '#e3e6ea', '--workspace-accent-border': '#aab1ba', '--workspace-accent-contrast': '#fafbfc',
        '--status-active': '#557a6e', '--status-cooling': '#90784f', '--status-abandoned': '#92696d', '--card-bg': '#fcfdfe',
      },
      dark: {
        '--ink': '#dde1e6', '--paper': '#101216', '--warm-gray': '#1e2127', '--muted': '#8b929c', '--th-color-text-secondary': '#adb4bd',
        '--accent-amber': '#ad9670', '--accent-chamomile': '#ada579', '--accent-slate': '#8995a2', '--accent-rose': '#b87c7f',
        '--workspace-accent': '#9aa3ac', '--workspace-accent-soft': '#1f2228', '--workspace-accent-border': '#586069', '--workspace-accent-contrast': '#0e1012',
        '--status-active': '#7aa099', '--status-cooling': '#ad9670', '--status-abandoned': '#b87a7e', '--card-bg': '#171a1e',
      },
    },
    'harbor-mist': {
      name: 'Harbor mist',
      nameKey: 'themeStyleHarborMistName',
      meta: 'Airy, low-pressure, cool',
      metaKey: 'themeStyleHarborMistMeta',
      shortMeta: 'Fog',
      tokens: {
        ...BASE_STYLE_TOKENS,
        '--th-display-weight': '400',
        '--th-display-tracking': '-0.03em',
        '--th-container-max': '1280px',
        '--th-column-gap': '48px',
        '--th-section-gap': '24px',
        '--th-panel-radius': 'var(--th-radius-xl)',
        '--th-card-radius': 'var(--th-radius-lg)',
        '--th-field-radius': 'var(--th-radius-lg)',
        '--th-page-texture-opacity': '0.018',
        '--th-surface-blur': '16px',
        '--th-item-shadow': '0 18px 42px color-mix(in srgb, var(--workspace-accent) 7%, transparent)',
        '--th-item-shadow-hover': '0 22px 48px color-mix(in srgb, var(--workspace-accent) 11%, transparent)',
      },
      light: {
        '--ink': '#151c22', '--paper': '#edf2f4', '--warm-gray': '#d7e0e4', '--muted': '#6f7d86', '--th-color-text-secondary': '#53636d',
        '--accent-amber': '#887159', '--accent-chamomile': '#a98f6b', '--accent-slate': '#4f6d80', '--accent-rose': '#91686e',
        '--workspace-accent': '#4f6f88', '--workspace-accent-soft': '#dbe7ef', '--workspace-accent-border': '#a5b7c5', '--workspace-accent-contrast': '#f7fbfd',
        '--status-active': '#557268', '--status-cooling': '#897252', '--status-abandoned': '#8e626b', '--card-bg': '#fbfdfe',
      },
      dark: {
        '--ink': '#dde5e8', '--paper': '#121920', '--warm-gray': '#222c33', '--muted': '#82909a', '--th-color-text-secondary': '#abb7bd',
        '--accent-amber': '#b09472', '--accent-chamomile': '#c4a576', '--accent-slate': '#83a5b8', '--accent-rose': '#bd8185',
        '--workspace-accent': '#8eb0c2', '--workspace-accent-soft': '#23303a', '--workspace-accent-border': '#526a78', '--workspace-accent-contrast': '#10181d',
        '--status-active': '#8aa99b', '--status-cooling': '#c1a176', '--status-abandoned': '#c78187', '--card-bg': '#19232b',
      },
    },
    'clay-notes': {
      name: 'Clay notes',
      nameKey: 'themeStyleClayNotesName',
      meta: 'Warm, personal, tactile',
      metaKey: 'themeStyleClayNotesMeta',
      shortMeta: 'Clay',
      tokens: {
        ...BASE_STYLE_TOKENS,
        '--th-display-weight': '500',
        '--th-display-tracking': '-0.028em',
        '--th-container-max': '1240px',
        '--th-column-gap': '38px',
        '--th-section-gap': '22px',
        '--th-card-gap': '13px',
        '--th-item-padding-y': '15px',
        '--th-item-padding-x': '17px',
        '--th-panel-radius': 'var(--th-radius-xl)',
        '--th-card-radius': 'var(--th-radius-lg)',
        '--th-control-radius': 'var(--th-radius-lg)',
        '--th-field-radius': 'var(--th-radius-lg)',
        '--th-page-texture-opacity': '0.035',
        '--th-surface-blur': '6px',
        '--th-item-shadow': '0 15px 30px color-mix(in srgb, var(--workspace-accent) 7%, transparent)',
        '--th-item-shadow-hover': '0 20px 38px color-mix(in srgb, var(--workspace-accent) 11%, transparent)',
      },
      light: {
        '--ink': '#221817', '--paper': '#f5eeeb', '--warm-gray': '#e5d6d1', '--muted': '#87716d', '--th-color-text-secondary': '#695653',
        '--accent-amber': '#96694f', '--accent-chamomile': '#ad8964', '--accent-slate': '#687176', '--accent-rose': '#9f5f5d',
        '--workspace-accent': '#946068', '--workspace-accent-soft': '#eedbdd', '--workspace-accent-border': '#cfa0a4', '--workspace-accent-contrast': '#fff7f6',
        '--status-active': '#5f7566', '--status-cooling': '#92704f', '--status-abandoned': '#995c5b', '--card-bg': '#fffaf7',
      },
      dark: {
        '--ink': '#eadfd9', '--paper': '#1a1212', '--warm-gray': '#2d2322', '--muted': '#9a817c', '--th-color-text-secondary': '#b8a4a0',
        '--accent-amber': '#bd8964', '--accent-chamomile': '#c8a47a', '--accent-slate': '#858e94', '--accent-rose': '#c78682',
        '--workspace-accent': '#c0838a', '--workspace-accent-soft': '#302323', '--workspace-accent-border': '#684a4d', '--workspace-accent-contrast': '#1a1212',
        '--status-active': '#8fa084', '--status-cooling': '#c7966f', '--status-abandoned': '#d08d88', '--card-bg': '#241a1a',
      },
    },
    'botanical-folio': {
      name: 'Botanical folio',
      nameKey: 'themeStyleBotanicalFolioName',
      meta: 'Pressed leaves, specimen paper, quiet',
      metaKey: 'themeStyleBotanicalFolioMeta',
      shortMeta: 'Herbarium',
      tokens: {
        ...BASE_STYLE_TOKENS,
        '--th-font-ui': BOOK_SERIF,
        '--th-font-display': BOOK_SERIF,
        '--th-font-section': BOOK_SERIF,
        '--th-display-weight': '500',
        '--th-display-tracking': '-0.022em',
        '--th-section-tracking': '0.035em',
        '--th-container-max': '1270px',
        '--th-column-gap': '44px',
        '--th-section-gap': '24px',
        '--th-card-gap': '14px',
        '--th-item-padding-y': '15px',
        '--th-item-padding-x': '17px',
        '--th-panel-radius': 'var(--th-radius-xl)',
        '--th-card-radius': 'var(--th-radius-md)',
        '--th-control-radius': 'var(--th-radius-md)',
        '--th-field-radius': 'var(--th-radius-lg)',
        '--th-page-texture-opacity': '0.065',
        '--th-surface-blur': '0px',
        '--th-item-shadow': '0 10px 28px color-mix(in srgb, var(--workspace-accent) 8%, transparent)',
        '--th-item-shadow-hover': '0 14px 32px color-mix(in srgb, var(--workspace-accent) 12%, transparent)',
        '--th-floating-shadow': '0 22px 50px color-mix(in srgb, var(--workspace-accent) 15%, transparent)',
        '--th-divider-opacity': '74%',
      },
      light: {
        '--ink': '#233026', '--paper': '#edf0e6', '--warm-gray': '#d5dacb', '--muted': '#6f7c70', '--th-color-text-secondary': '#4f5f52',
        '--accent-amber': '#8b6a43', '--accent-chamomile': '#a28f5c', '--accent-slate': '#5d7068', '--accent-rose': '#8c635f',
        '--workspace-accent': '#4f6a52', '--workspace-accent-soft': '#dbe5d6', '--workspace-accent-border': '#9caf98', '--workspace-accent-contrast': '#fbfdf7',
        '--status-active': '#4f7255', '--status-cooling': '#8b713d', '--status-abandoned': '#8c5f58', '--card-bg': '#f9faf4',
      },
      dark: {
        '--ink': '#e4eadf', '--paper': '#121812', '--warm-gray': '#242d23', '--muted': '#8f9d8d', '--th-color-text-secondary': '#b5c1b2',
        '--accent-amber': '#bd9560', '--accent-chamomile': '#c0aa70', '--accent-slate': '#8da29a', '--accent-rose': '#bd827b',
        '--workspace-accent': '#91aa8e', '--workspace-accent-soft': '#273326', '--workspace-accent-border': '#576d55', '--workspace-accent-contrast': '#10170f',
        '--status-active': '#8eae90', '--status-cooling': '#c0a267', '--status-abandoned': '#c7857d', '--card-bg': '#1b231a',
      },
    },
    'porcelain-atlas': {
      name: 'Porcelain atlas',
      nameKey: 'themeStylePorcelainAtlasName',
      meta: 'Cobalt lines, glazed ivory, mapped',
      metaKey: 'themeStylePorcelainAtlasMeta',
      shortMeta: 'Cobalt',
      tokens: {
        ...BASE_STYLE_TOKENS,
        '--th-font-ui': CJK_SERIF,
        '--th-font-display': CJK_SERIF,
        '--th-font-section': CJK_SERIF,
        '--th-display-weight': '500',
        '--th-display-tracking': '-0.012em',
        '--th-section-tracking': '0.08em',
        '--th-container-max': '1300px',
        '--th-column-gap': '50px',
        '--th-section-gap': '20px',
        '--th-card-gap': '10px',
        '--th-item-padding-y': '13px',
        '--th-item-padding-x': '15px',
        '--th-panel-radius': 'var(--th-radius-lg)',
        '--th-card-radius': 'var(--th-radius-sm)',
        '--th-control-radius': 'var(--th-radius-sm)',
        '--th-field-radius': 'var(--th-radius-md)',
        '--th-page-texture-opacity': '0.016',
        '--th-surface-blur': '2px',
        '--th-item-shadow': 'none',
        '--th-item-shadow-hover': 'inset 0 0 0 1px color-mix(in srgb, var(--workspace-accent) 20%, transparent)',
        '--th-floating-shadow': '0 18px 44px color-mix(in srgb, var(--workspace-accent) 13%, transparent)',
        '--th-hover-lift': '0px',
        '--th-divider-opacity': '88%',
      },
      light: {
        '--ink': '#18283b', '--paper': '#eef2f3', '--warm-gray': '#d5dfe3', '--muted': '#6a7885', '--th-color-text-secondary': '#4b5d6e',
        '--accent-amber': '#9a7040', '--accent-chamomile': '#ad9260', '--accent-slate': '#426b8c', '--accent-rose': '#8d5d63',
        '--workspace-accent': '#315f8c', '--workspace-accent-soft': '#d9e7f0', '--workspace-accent-border': '#8ba9c3', '--workspace-accent-contrast': '#fbfdff',
        '--status-active': '#4f7168', '--status-cooling': '#8e713f', '--status-abandoned': '#8b5c5f', '--card-bg': '#f9fbfa',
      },
      dark: {
        '--ink': '#e3ebf3', '--paper': '#0f1822', '--warm-gray': '#22303d', '--muted': '#8c9baa', '--th-color-text-secondary': '#adbdcb',
        '--accent-amber': '#c89a62', '--accent-chamomile': '#c6ad77', '--accent-slate': '#86afd0', '--accent-rose': '#c2848b',
        '--workspace-accent': '#81abd2', '--workspace-accent-soft': '#21354a', '--workspace-accent-border': '#4f7395', '--workspace-accent-contrast': '#0d1720',
        '--status-active': '#85a99d', '--status-cooling': '#c3a06c', '--status-abandoned': '#c47f83', '--card-bg': '#172432',
      },
    },
    'nocturne-observatory': {
      name: 'Nocturne observatory',
      nameKey: 'themeStyleNocturneObservatoryName',
      meta: 'Celestial ink, brass measures, nocturnal',
      metaKey: 'themeStyleNocturneObservatoryMeta',
      shortMeta: 'Celestial',
      tokens: {
        ...BASE_STYLE_TOKENS,
        '--th-font-ui': BOOK_SERIF,
        '--th-font-display': BOOK_SERIF,
        '--th-font-section': BOOK_SERIF,
        '--th-display-weight': '400',
        '--th-display-tracking': '-0.04em',
        '--th-section-tracking': '0.04em',
        '--th-container-max': '1260px',
        '--th-column-gap': '46px',
        '--th-section-gap': '26px',
        '--th-card-gap': '12px',
        '--th-item-padding-y': '15px',
        '--th-item-padding-x': '17px',
        '--th-panel-radius': 'var(--th-radius-xl)',
        '--th-card-radius': 'var(--th-radius-lg)',
        '--th-control-radius': 'var(--th-radius-pill)',
        '--th-field-radius': 'var(--th-radius-pill)',
        '--th-page-texture-opacity': '0.025',
        '--th-surface-blur': '18px',
        '--th-item-shadow': '0 18px 44px color-mix(in srgb, var(--workspace-accent) 9%, transparent)',
        '--th-item-shadow-hover': '0 24px 52px color-mix(in srgb, var(--workspace-accent) 14%, transparent)',
        '--th-floating-shadow': '0 28px 68px color-mix(in srgb, black 24%, transparent)',
        '--th-divider-opacity': '58%',
      },
      light: {
        '--ink': '#1c2132', '--paper': '#edeef5', '--warm-gray': '#d7d8e4', '--muted': '#6d7183', '--th-color-text-secondary': '#50566b',
        '--accent-amber': '#9a7441', '--accent-chamomile': '#ae9360', '--accent-slate': '#596b91', '--accent-rose': '#845e78',
        '--workspace-accent': '#505f8f', '--workspace-accent-soft': '#dfe3f1', '--workspace-accent-border': '#a0a9c9', '--workspace-accent-contrast': '#fcfcff',
        '--status-active': '#587269', '--status-cooling': '#8d7040', '--status-abandoned': '#855d6d', '--card-bg': '#f8f8fc',
      },
      dark: {
        '--ink': '#e8eaf3', '--paper': '#0c101a', '--warm-gray': '#22283a', '--muted': '#9197aa', '--th-color-text-secondary': '#b9bfd0',
        '--accent-amber': '#c6a066', '--accent-chamomile': '#d0b479', '--accent-slate': '#9aa9d0', '--accent-rose': '#bc839f',
        '--workspace-accent': '#929fd0', '--workspace-accent-soft': '#222a41', '--workspace-accent-border': '#56628a', '--workspace-accent-contrast': '#0b0e17',
        '--status-active': '#8eaca1', '--status-cooling': '#c9a66c', '--status-abandoned': '#c8869f', '--card-bg': '#151b2a',
      },
    },
    'vermilion-seal': {
      name: 'Vermilion seal',
      nameKey: 'themeStyleVermilionSealName',
      meta: 'Rice paper, ink, ceremonial marks',
      metaKey: 'themeStyleVermilionSealMeta',
      shortMeta: 'Cinnabar',
      tokens: {
        ...BASE_STYLE_TOKENS,
        '--th-font-ui': CJK_SERIF,
        '--th-font-display': CJK_SERIF,
        '--th-font-section': CJK_SERIF,
        '--th-display-weight': '500',
        '--th-display-tracking': '0.005em',
        '--th-section-tracking': '0.12em',
        '--th-container-max': '1210px',
        '--th-column-gap': '36px',
        '--th-section-gap': '18px',
        '--th-card-gap': '8px',
        '--th-item-padding-y': '12px',
        '--th-item-padding-x': '14px',
        '--th-panel-radius': 'var(--th-radius-md)',
        '--th-card-radius': 'var(--th-radius-sm)',
        '--th-control-radius': 'var(--th-radius-sm)',
        '--th-field-radius': 'var(--th-radius-sm)',
        '--th-page-texture-opacity': '0.05',
        '--th-surface-blur': '0px',
        '--th-item-shadow': '3px 4px 0 color-mix(in srgb, var(--workspace-accent) 8%, transparent)',
        '--th-item-shadow-hover': '4px 5px 0 color-mix(in srgb, var(--workspace-accent) 12%, transparent)',
        '--th-floating-shadow': '8px 10px 0 color-mix(in srgb, var(--workspace-accent) 12%, transparent)',
        '--th-hover-lift': '0px',
        '--th-divider-opacity': '90%',
      },
      light: {
        '--ink': '#2a1d19', '--paper': '#f3ede3', '--warm-gray': '#ddd0c2', '--muted': '#7b6b63', '--th-color-text-secondary': '#5f4f48',
        '--accent-amber': '#956039', '--accent-chamomile': '#aa8450', '--accent-slate': '#66706d', '--accent-rose': '#a14838',
        '--workspace-accent': '#9d3f30', '--workspace-accent-soft': '#f0d9d0', '--workspace-accent-border': '#c78a7d', '--workspace-accent-contrast': '#fff9f4',
        '--status-active': '#5c725d', '--status-cooling': '#916b39', '--status-abandoned': '#9d3f30', '--card-bg': '#fffaf1',
      },
      dark: {
        '--ink': '#f0dfd5', '--paper': '#1a1110', '--warm-gray': '#32231f', '--muted': '#a28b81', '--th-color-text-secondary': '#c8b0a5',
        '--accent-amber': '#c88755', '--accent-chamomile': '#d0a267', '--accent-slate': '#8f9b96', '--accent-rose': '#d0705b',
        '--workspace-accent': '#d36b56', '--workspace-accent-soft': '#3a2420', '--workspace-accent-border': '#80483d', '--workspace-accent-contrast': '#190f0d',
        '--status-active': '#91a48e', '--status-cooling': '#c99759', '--status-abandoned': '#d0705b', '--card-bg': '#261916',
      },
    },
  };

  function resolveKnownStyleId(value) {
    const rawId = String(value || '').trim();
    if (STYLE_ORDER.includes(rawId)) return rawId;
    return STYLE_ALIASES[rawId] || null;
  }

  function normalizeStyleId(value) {
    return resolveKnownStyleId(value) || 'paper-desk';
  }

  function getStyle(value) {
    return STYLE_DEFINITIONS[normalizeStyleId(value)];
  }

  function getLegacyPaletteId(value) {
    return LEGACY_PALETTE_IDS[normalizeStyleId(value)] || 'paper';
  }

  function getPreviewStyle(value) {
    const style = getStyle(value);
    const light = style.light;
    const dark = style.dark;
    return [
      `--theme-paper:${light['--paper']}`,
      `--theme-surface:${light['--card-bg']}`,
      `--theme-accent:${light['--workspace-accent']}`,
      `--theme-ink:${light['--ink']}`,
      `--theme-dark:${dark['--paper']}`,
    ].join(';');
  }

  globalThis.TabHarborThemeCatalog = Object.freeze({
    MODE_ORDER,
    STYLE_ORDER,
    STYLE_ALIASES,
    LEGACY_THEME_MIGRATION,
    REQUIRED_TONE_TOKENS,
    STYLE_DEFINITIONS,
    resolveKnownStyleId,
    normalizeStyleId,
    getStyle,
    getLegacyPaletteId,
    getPreviewStyle,
  });
})();
